package Project.Common;

public enum PayloadType {
    CLIENT_CONNECT,
    JOIN_SPECTATOR,
    CLIENT_ID,
    SYNC_CLIENT,
    DISCONNECT,
    ROOM_CREATE,
    ROOM_JOIN,
    ROOM_REMOVE,
    ROOM_LEAVE,
    ROOM_LIST,
    ROOM_CLEAR,
    REVERSE,
    MESSAGE,
    GAME_READY,
    TOGGLE_AWAY,
    GAME_PICK,
    GAME_RESULT,
    GAME_STATE,
    ROUND_START,
    ROUND_END,
    PLAYER_ELIMINATED,
    PLAYER_STATUS,
    SCOREBOARD,
    SESSION_START,
    RESET_GAME_STATE, // For resetting UI after a game
    SYNC_POINTS,
    SESSION_END
}